# Generated by Django 5.2.1 on 2025-05-26 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_client_age'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
