# Generated by Django 5.2.1 on 2025-06-03 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_photo_client_date_added'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
