# Generated by Django 5.2.1 on 2025-06-03 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_delete_photo'),
    ]

    operations = [
    ]
