# Generated by Django 5.2.1 on 2025-06-03 12:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20250603_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.DateField(default=datetime.date(2007, 6, 3)),
        ),
    ]
