# Generated by Django 5.2.1 on 2025-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0012_alter_client_age_cart_order_orderitem_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название сертификата')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('certificate_number', models.CharField(max_length=100, verbose_name='Номер сертификата')),
                ('issued_by', models.CharField(max_length=200, verbose_name='Выдан')),
                ('issued_date', models.DateField(verbose_name='Дата выдачи')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='company/certificates/', verbose_name='Файл сертификата')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/certificates/', verbose_name='Изображение сертификата')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сертификат компании',
                'verbose_name_plural': 'Сертификаты компании',
                'ordering': ['order', '-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='CompanyHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='Год')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок события')),
                ('description', models.TextField(verbose_name='Описание события')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company/history/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'История компании',
                'verbose_name_plural': 'История компании',
                'ordering': ['-year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название компании')),
                ('description', models.TextField(verbose_name='Описание компании')),
                ('mission', models.TextField(blank=True, verbose_name='Миссия компании')),
                ('vision', models.TextField(blank=True, verbose_name='Видение компании')),
                ('values', models.TextField(blank=True, verbose_name='Ценности компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company/', verbose_name='Логотип')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Ссылка на видео')),
                ('founded_year', models.PositiveIntegerField(verbose_name='Год основания')),
                ('employees_count', models.PositiveIntegerField(default=0, verbose_name='Количество сотрудников')),
                ('clients_count', models.PositiveIntegerField(default=0, verbose_name='Количество клиентов')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Информация о компании',
                'verbose_name_plural': 'Информация о компании',
            },
        ),
        migrations.CreateModel(
            name='CompanyRequisites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(max_length=200, verbose_name='Юридическое название')),
                ('inn', models.CharField(max_length=12, verbose_name='ИНН')),
                ('kpp', models.CharField(blank=True, max_length=9, verbose_name='КПП')),
                ('ogrn', models.CharField(max_length=15, verbose_name='ОГРН')),
                ('legal_address', models.TextField(verbose_name='Юридический адрес')),
                ('actual_address', models.TextField(verbose_name='Фактический адрес')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('bank_name', models.CharField(max_length=200, verbose_name='Название банка')),
                ('bank_account', models.CharField(max_length=20, verbose_name='Расчетный счет')),
                ('correspondent_account', models.CharField(max_length=20, verbose_name='Корреспондентский счет')),
                ('bik', models.CharField(max_length=9, verbose_name='БИК')),
                ('director_name', models.CharField(max_length=100, verbose_name='ФИО директора')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активны')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Реквизиты компании',
                'verbose_name_plural': 'Реквизиты компании',
            },
        ),
    ]
