# Generated by Django 5.2.1 on 2025-09-14 12:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0014_newsarticle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='term',
            options={'ordering': ['order', '-added_date'], 'verbose_name': 'Термин/FAQ', 'verbose_name_plural': 'Термины/FAQ'},
        ),
        migrations.RemoveField(
            model_name='term',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='term',
            name='term',
        ),
        migrations.AddField(
            model_name='term',
            name='answer',
            field=models.TextField(default='-', verbose_name='Ответ'),
        ),
        migrations.AddField(
            model_name='term',
            name='category',
            field=models.CharField(default='Общие', max_length=100, verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='term',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='term',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AddField(
            model_name='term',
            name='question',
            field=models.CharField(default='-', max_length=200, verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='term',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='term',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='term',
            name='added_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата добавления'),
        ),
    ]
