# Generated by Django 5.2.1 on 2025-09-18 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0015_alter_term_options_remove_term_definition_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontact',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='employeecontact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employees/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.DateField(default=datetime.date(2007, 9, 18)),
        ),
    ]
