# Generated by Django 5.2.1 on 2025-09-21 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0016_remove_employeecontact_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeecontact',
            name='photo',
        ),
        migrations.AddField(
            model_name='employeecontact',
            name='photo_path',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='client',
            name='age',
            field=models.DateField(default=datetime.date(2007, 9, 21)),
        ),
    ]
