# Generated by Django 5.2.1 on 2025-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0017_remove_employeecontact_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeecontact',
            name='photo_path',
            field=models.CharField(blank=True, choices=[('', 'Нет фото'), ('images/worker1.jpeg', 'Worker 1'), ('images/worker2.jpeg', 'Worker 2'), ('images/worker3.jpeg', 'Worker 3'), ('images/worker4.jpeg', 'Worker 4')], max_length=255, null=True, verbose_name='Путь к фото'),
        ),
        migrations.AlterField(
            model_name='term',
            name='category',
            field=models.CharField(choices=[('parking', 'Вопросы по поводу парковки'), ('staff', 'Жалобы на обслуживание персонала'), ('other', 'Иные жалобы')], default='parking', max_length=100, verbose_name='Категория'),
        ),
    ]
