# Generated by Django 5.2.1 on 2025-05-25 16:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='age',
            field=models.PositiveIntegerField(default=18, help_text='Возраст должен быть от 18 до 120 лет', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(120)]),
            preserve_default=False,
        ),
    ]
